
service: show-me-a-dog

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10
  region: ca-central-1

functions:
  list:
    handler: handler.list
    events:
      - http:
          path: /
          method: get
  show:
    handler: handler.show
    events:
      - http:
          path: /{breed}
          method: get
